import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo App | Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='min-h-screen'>
        <h1>Helloo</h1>
      </main>
    </>
  );
}
