import Head from 'next/head';
import Header from './Header';

type Props = {
  title?: string;
  description?: string;
  children: React.ReactNode;
};

function Layout({
  title = 'Todo App',
  description = 'Generated by create next app',
  children,
}: Props) {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name='description' content={description} />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main className='bg-gray-900 text-white'>{children}</main>
    </>
  );
}

export default Layout;
